import type { Resource } from "@/types/resources";

export const resourceTypes = [
  "All",
  "Documentation",
  "Guide",
  "Exercise",
  "Tool",
  "Playground",
  "Generator",
] as const;

export const resourceCategories = [
  "All",
  "HTML",
  "CSS",
  "JS",
  "Git",
  "SQL",
  "Tools",
  "General",
] as const;

export const resources: Resource[] = [
  // --- HTML ---
  {
    id: "mdn-html",
    title: "MDN HTML Documentation",
    description: "The definitive source for HTML documentation and tutorials.",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    category: "HTML",
    type: "Documentation",
    tags: ["Reference", "Beginner", "Official"],
  },
  {
    id: "html-reference",
    title: "HTML Reference",
    description: "A free guide to all HTML elements and attributes.",
    url: "https://htmlreference.io",
    category: "HTML",
    type: "Documentation",
    tags: ["Reference", "Visual"],
  },
  {
    id: "html5book",
    title: "HTML5 Book",
    description: "Comprehensive Russian guide to HTML5 and web development.",
    url: "https://html5book.ru/",
    category: "HTML",
    type: "Guide",
    tags: ["Russian", "Reference"],
  },
  {
    id: "interneting-is-hard",
    title: "Interneting Is Hard",
    description: "Friendly web development tutorials for complete beginners.",
    url: "https://internetingishard.netlify.app/",
    category: "HTML",
    type: "Guide",
    tags: ["Beginner", "Visual"],
  },

  // --- CSS ---
  {
    id: "css-tricks",
    title: "CSS-Tricks",
    description:
      "A website about websites. Excellent for deep dives into CSS layouts and modern techniques.",
    url: "https://css-tricks.com",
    category: "CSS",
    type: "Guide",
    tags: ["Articles", "Advanced", "Layout"],
  },
  {
    id: "flexbox-froggy",
    title: "Flexbox Froggy",
    description:
      "A game for learning CSS flexbox by helping Froggy and friends.",
    url: "https://flexboxfroggy.com",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Interactive", "Flexbox"],
  },
  {
    id: "grid-garden",
    title: "Grid Garden",
    description: "Learn CSS Grid by writing code to grow your carrot garden.",
    url: "https://cssgridgarden.com",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Interactive", "Grid"],
  },
  {
    id: "css-reference",
    title: "CSS Reference",
    description:
      "A free visual guide to CSS. It features the most popular properties and explains them with illustrated and animated examples.",
    url: "https://cssreference.io",
    category: "CSS",
    type: "Documentation",
    tags: ["Visual", "Reference"],
  },
  {
    id: "cssbattle",
    title: "CSS Battle",
    description:
      "Use your CSS skills to replicate targets with the smallest possible code.",
    url: "https://cssbattle.dev/",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Competition", "Code Golf"],
  },
  {
    id: "flukeout",
    title: "CSS Diner",
    description: "A fun game to learn and practice CSS selectors.",
    url: "https://flukeout.github.io/",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Selectors"],
  },
  {
    id: "flexbox-defense",
    title: "Flexbox Defense",
    description:
      "A tower defense game where you use flexbox to position your towers.",
    url: "http://www.flexboxdefense.com/",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Flexbox"],
  },
  {
    id: "knights-flexbox",
    title: "Knights of the Flexbox Table",
    description: "Learn flexbox through a series of knightly challenges.",
    url: "https://knightsoftheflexboxtable.com/",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Flexbox"],
  },
  {
    id: "100dayscss",
    title: "100 Days CSS Challenge",
    description:
      "Improve your CSS skills with a new challenge every day for 100 days.",
    url: "https://100dayscss.com/",
    category: "CSS",
    type: "Exercise",
    tags: ["Challenge", "Daily"],
  },
  {
    id: "animista",
    title: "Animista",
    description:
      "A place where you can play with a collection of ready to use CSS animations.",
    url: "https://animista.net/",
    category: "CSS",
    type: "Generator",
    tags: ["Animation", "Visual"],
  },
  {
    id: "cssgradient",
    title: "CSS Gradient",
    description:
      "A free tool that lets you create a gradient background for websites.",
    url: "https://cssgradient.io/",
    category: "CSS",
    type: "Generator",
    tags: ["Gradient", "Visual"],
  },
  {
    id: "neumorphism",
    title: "Neumorphism.io",
    description: "Generate Soft-UI CSS code for your designs.",
    url: "https://neumorphism.io/",
    category: "CSS",
    type: "Generator",
    tags: ["Design", "Neumorphism"],
  },
  {
    id: "getwaves",
    title: "Get Waves",
    description:
      "A free SVG wave generator to make unique SVG waves for your next web design.",
    url: "https://getwaves.io/",
    category: "CSS",
    type: "Generator",
    tags: ["SVG", "Waves"],
  },
  {
    id: "grid-layoutit",
    title: "CSS Grid Generator",
    description:
      "Set the numbers and units of your columns and rows, and we'll generate a CSS grid for you!",
    url: "https://grid.layoutit.com/",
    category: "CSS",
    type: "Generator",
    tags: ["Grid", "Layout"],
  },
  {
    id: "css-glass",
    title: "Glassmorphism Generator",
    description: "Generate CSS for glassmorphism effects.",
    url: "https://css.glass/",
    category: "CSS",
    type: "Generator",
    tags: ["Glassmorphism", "Design"],
  },
  {
    id: "flexboxpatterns",
    title: "Flexbox Patterns",
    description: "A collection of user interface patterns for flexbox.",
    url: "https://flexboxpatterns.com/",
    category: "CSS",
    type: "Guide",
    tags: ["Patterns", "Flexbox"],
  },
  {
    id: "moderncss",
    title: "Modern CSS",
    description: "Modern CSS solutions for old CSS problems.",
    url: "https://moderncss.dev/",
    category: "CSS",
    type: "Guide",
    tags: ["Modern", "Advanced"],
  },
  {
    id: "css-grid-generator-netlify",
    title: "CSS Grid Generator (Netlify)",
    description: "A simple tool to generate CSS grid layouts.",
    url: "https://cssgrid-generator.netlify.app/",
    category: "CSS",
    type: "Generator",
    tags: ["Grid", "Layout"],
  },
  {
    id: "cssgridgenerator-io",
    title: "CSS Grid Generator (IO)",
    description: "Another excellent CSS grid layout generator.",
    url: "https://cssgridgenerator.io/",
    category: "CSS",
    type: "Generator",
    tags: ["Grid", "Layout"],
  },
  {
    id: "codingfantasy",
    title: "Coding Fantasy",
    description: "Learn CSS through fun games and challenges.",
    url: "https://codingfantasy.com/",
    category: "CSS",
    type: "Exercise",
    tags: ["Game", "Interactive"],
  },
  {
    id: "bennettfeely",
    title: "Bennett Feely Tools",
    description: "A collection of CSS tools like Clippy (clip-path maker).",
    url: "https://bennettfeely.com/",
    category: "CSS",
    type: "Tool",
    tags: ["Clip-path", "Design"],
  },
  {
    id: "huemint",
    title: "Huemint",
    description: "AI color palette generator for your next project.",
    url: "https://huemint.com/",
    category: "CSS",
    type: "Generator",
    tags: ["Colors", "AI"],
  },
  {
    id: "specificity-keegan",
    title: "CSS Specificity",
    description: "A visual guide to CSS specificity.",
    url: "https://specificity.keegan.st/",
    category: "CSS",
    type: "Documentation",
    tags: ["Specificity", "Visual"],
  },
  {
    id: "css-portal",
    title: "CSS Portal",
    description: "A collection of CSS generators, tools, and resources.",
    url: "https://www.cssportal.com/",
    category: "CSS",
    type: "Tool",
    tags: ["Generators", "Reference"],
  },
  {
    id: "caniuse",
    title: "Can I Use",
    description: "Browser support tables for modern web technologies.",
    url: "https://caniuse.com/",
    category: "CSS",
    type: "Documentation",
    tags: ["Browser Support", "Reference"],
  },
  {
    id: "caniemail",
    title: "Can I Email",
    description: "Support tables for HTML and CSS in email clients.",
    url: "https://www.caniemail.com/",
    category: "CSS",
    type: "Documentation",
    tags: ["Email", "Reference"],
  },

  // --- JS ---
  {
    id: "javascript-info",
    title: "The Modern JavaScript Tutorial",
    description:
      "From the basics to advanced topics with simple, but detailed explanations.",
    url: "https://javascript.info",
    category: "JS",
    type: "Guide",
    tags: ["Comprehensive", "Deep Dive"],
  },
  {
    id: "codewars",
    title: "Codewars",
    description:
      "Improve your skills by training with others on real code challenges.",
    url: "https://www.codewars.com",
    category: "JS",
    type: "Exercise",
    tags: ["Challenges", "Problem Solving"],
  },
  {
    id: "javascript-30",
    title: "JavaScript 30",
    description:
      "Build 30 things in 30 days with 30 tutorials. No libraries, no frameworks.",
    url: "https://javascript30.com",
    category: "JS",
    type: "Exercise",
    tags: ["Vanilla JS", "Projects", "Video"],
  },
  {
    id: "leetcode",
    title: "LeetCode",
    description:
      "The best platform to help you enhance your skills, expand your knowledge and prepare for technical interviews.",
    url: "https://leetcode.com/",
    category: "JS",
    type: "Exercise",
    tags: ["Interview", "Algorithms", "Data Structures"],
  },
  {
    id: "jschallenger",
    title: "JS Challenger",
    description: "Learn Javascript by solving coding challenges.",
    url: "https://www.jschallenger.com/",
    category: "JS",
    type: "Exercise",
    tags: ["Challenges", "Beginner"],
  },
  {
    id: "eloquent-javascript",
    title: "Eloquent JavaScript",
    description:
      "A modern introduction to programming and the JavaScript language.",
    url: "https://eloquentjavascript.net/",
    category: "JS",
    type: "Guide",
    tags: ["Book", "Comprehensive"],
  },
  {
    id: "learn-js-org",
    title: "Learn-JS.org",
    description: "Interactive JavaScript tutorial for beginners.",
    url: "https://www.learn-js.org/",
    category: "JS",
    type: "Exercise",
    tags: ["Tutorial", "Interactive"],
  },
  {
    id: "edabit",
    title: "Edabit",
    description: "Learn to code with 10,000+ interactive challenges.",
    url: "https://edabit.com/",
    category: "JS",
    type: "Exercise",
    tags: ["Challenges", "Interactive"],
  },
  {
    id: "bigfrontend",
    title: "BigFrontend",
    description: "Prepare for front-end interviews with coding challenges.",
    url: "https://bigfrontend.dev/",
    category: "JS",
    type: "Exercise",
    tags: ["Interview", "Challenges"],
  },
  {
    id: "30-seconds-of-code",
    title: "30 Seconds of Code",
    description:
      "Short JavaScript code snippets for all your development needs.",
    url: "https://www.30secondsofcode.org/",
    category: "JS",
    type: "Guide",
    tags: ["Snippets", "Reference"],
  },

  // --- General ---
  {
    id: "freecodecamp",
    title: "freeCodeCamp",
    description:
      "Interactive coding platform with thousands of hours of free curriculum.",
    url: "https://www.freecodecamp.org",
    category: "General",
    type: "Exercise",
    tags: ["Certification", "Full Stack", "Community"],
  },
  {
    id: "web-dev",
    title: "web.dev",
    description:
      "Google's platform for web developers to learn about performance, accessibility, and modern web APIs.",
    url: "https://web.dev",
    category: "General",
    type: "Guide",
    tags: ["Performance", "Best Practices", "Google"],
  },
  {
    id: "frontend-mentor",
    title: "Frontend Mentor",
    description:
      "Improve your front-end skills by building real projects. Solve real-world HTML, CSS and JS challenges.",
    url: "https://www.frontendmentor.io",
    category: "General",
    type: "Exercise",
    tags: ["Projects", "Design", "Portfolio"],
  },
  {
    id: "w3schools",
    title: "W3Schools",
    description:
      "The world's largest web developer site with tutorials and references.",
    url: "https://www.w3schools.com/",
    category: "General",
    type: "Documentation",
    tags: ["Beginner", "Reference"],
  },
  {
    id: "theodinproject",
    title: "The Odin Project",
    description:
      "Your career in web development starts here. A full stack curriculum that is free and open source.",
    url: "https://www.theodinproject.com/",
    category: "General",
    type: "Guide",
    tags: ["Full Stack", "Curriculum"],
  },
  {
    id: "fullstackopen",
    title: "Full Stack Open",
    description:
      "Learn React, Redux, Node.js, MongoDB, GraphQL and TypeScript in one go!",
    url: "https://fullstackopen.com/",
    category: "General",
    type: "Guide",
    tags: ["University", "Advanced", "Full Stack"],
  },
  {
    id: "roadmap-sh",
    title: "Developer Roadmaps",
    description:
      "Step by step guides and paths to learn different technologies.",
    url: "https://roadmap.sh/",
    category: "General",
    type: "Guide",
    tags: ["Career", "Learning Path"],
  },
  {
    id: "a11yproject",
    title: "The A11Y Project",
    description:
      "A community-driven effort to make digital accessibility easier.",
    url: "https://www.a11yproject.com/",
    category: "General",
    type: "Guide",
    tags: ["Accessibility", "Best Practices"],
  },
  {
    id: "patterns-dev",
    title: "Patterns.dev",
    description:
      "A free book on design patterns and component patterns for building powerful web apps.",
    url: "https://www.patterns.dev/",
    category: "General",
    type: "Guide",
    tags: ["Design Patterns", "Architecture"],
  },
  {
    id: "inclusive-components",
    title: "Inclusive Components",
    description:
      "A blog trying to be a pattern library, with a focus on accessibility.",
    url: "https://inclusive-components.design/",
    category: "General",
    type: "Guide",
    tags: ["Accessibility", "Components"],
  },
  {
    id: "http-dev",
    title: "HTTP.dev",
    description: "A comprehensive guide to the HTTP protocol.",
    url: "https://http.dev/",
    category: "General",
    type: "Documentation",
    tags: ["HTTP", "Networking"],
  },

  // --- Git ---
  {
    id: "git-tower",
    title: "Git Tower Learn",
    description: "Learn Git with the best tutorials, videos, and cheat sheets.",
    url: "https://www.git-tower.com/learn/git/ebook/en/command-line/introduction",
    category: "Git",
    type: "Guide",
    tags: ["Version Control", "Ebook"],
  },
  {
    id: "learngitbranching",
    title: "Learn Git Branching",
    description:
      "An interactive Git visualization tool to learn Git branching.",
    url: "https://learngitbranching.js.org/",
    category: "Git",
    type: "Exercise",
    tags: ["Interactive", "Visualization"],
  },
  {
    id: "githowto",
    title: "Git How To",
    description: "A guided tour that walks through the fundamentals of Git.",
    url: "https://githowto.com/",
    category: "Git",
    type: "Guide",
    tags: ["Tutorial", "Fundamentals"],
  },
  {
    id: "ohshitgit",
    title: "Oh Shit, Git!?!",
    description:
      "Git is hard: screwing up is easy, and figuring out how to fix your mistakes is barely documented.",
    url: "https://ohshitgit.com/",
    category: "Git",
    type: "Guide",
    tags: ["Troubleshooting", "Humor"],
  },
  {
    id: "conventionalcommits",
    title: "Conventional Commits",
    description:
      "A specification for adding human and machine readable meaning to commit messages.",
    url: "https://www.conventionalcommits.org/",
    category: "Git",
    type: "Documentation",
    tags: ["Best Practices", "Workflow"],
  },
  {
    id: "git-gaozih",
    title: "Git Cheat Sheet (Chinese)",
    description: "A comprehensive Git cheat sheet in Chinese.",
    url: "https://git.gaozih.com/",
    category: "Git",
    type: "Documentation",
    tags: ["Chinese", "Cheat Sheet"],
  },

  // --- SQL ---
  {
    id: "sqlbolt",
    title: "SQLBolt",
    description: "Learn SQL with interactive exercises.",
    url: "https://sqlbolt.com/",
    category: "SQL",
    type: "Exercise",
    tags: ["Database", "Interactive"],
  },
  {
    id: "sqlzoo",
    title: "SQLZoo",
    description: "Interactive SQL tutorial with many examples and quizzes.",
    url: "https://sqlzoo.net/",
    category: "SQL",
    type: "Exercise",
    tags: ["Database", "Interactive"],
  },
  {
    id: "selectstarsql",
    title: "Select Star SQL",
    description:
      "An interactive SQL book which aims to be the best place on the internet for learning SQL.",
    url: "https://selectstarsql.com/",
    category: "SQL",
    type: "Guide",
    tags: ["Database", "Book"],
  },
  {
    id: "learn-mongodb",
    title: "MongoDB University",
    description: "Free online courses for learning MongoDB.",
    url: "https://learn.mongodb.com/",
    category: "SQL",
    type: "Guide",
    tags: ["NoSQL", "Database"],
  },
  {
    id: "sql-mystery",
    title: "SQL Murder Mystery",
    description: "A fun game to learn SQL by solving a murder mystery.",
    url: "https://mystery.knightlab.com/",
    category: "SQL",
    type: "Exercise",
    tags: ["Game", "Interactive"],
  },
  {
    id: "db-fiddle",
    title: "DB Fiddle",
    description: "An online SQL playground for testing and sharing queries.",
    url: "https://www.db-fiddle.com/",
    category: "SQL",
    type: "Playground",
    tags: ["Database", "Testing"],
  },

  // --- Tools ---
  {
    id: "stackblitz",
    title: "StackBlitz",
    description: "The fastest, most secure dev environment on the planet.",
    url: "https://stackblitz.com/",
    category: "Tools",
    type: "Playground",
    tags: ["IDE", "Online"],
  },
  {
    id: "play-tailwindcss",
    title: "Tailwind Play",
    description: "An advanced online playground for Tailwind CSS.",
    url: "https://play.tailwindcss.com/",
    category: "Tools",
    type: "Playground",
    tags: ["CSS", "Tailwind"],
  },
  {
    id: "devdocs",
    title: "DevDocs",
    description:
      "Combines multiple API documentations in a fast, organized, and searchable interface.",
    url: "https://devdocs.io/",
    category: "Tools",
    type: "Documentation",
    tags: ["Reference", "Offline"],
  },
  {
    id: "regex101",
    title: "Regex101",
    description:
      "Online regex tester and debugger: PHP, PCRE, Python, Golang and JavaScript.",
    url: "https://regex101.com/",
    category: "Tools",
    type: "Tool",
    tags: ["Regex", "Debugger"],
  },
  {
    id: "postman",
    title: "Postman",
    description:
      "The world's leading API platform for building and using APIs.",
    url: "https://www.postman.com/",
    category: "Tools",
    type: "Tool",
    tags: ["API", "Testing"],
  },
  {
    id: "uiverse",
    title: "Uiverse",
    description: "Open-source UI elements for any project.",
    url: "https://uiverse.io/",
    category: "Tools",
    type: "Tool",
    tags: ["UI", "Components"],
  },
  {
    id: "squoosh",
    title: "Squoosh",
    description:
      "Squoosh is the ultimate image optimizer that allows you to compress and compare images with different codecs in your browser.",
    url: "https://squoosh.app/",
    category: "Tools",
    type: "Tool",
    tags: ["Images", "Optimization"],
  },
  {
    id: "svgrepo",
    title: "SVG Repo",
    description:
      "Search, explore and edit the best-fitting free icons or vectors for your projects.",
    url: "https://www.svgrepo.com/",
    category: "Tools",
    type: "Tool",
    tags: ["SVG", "Icons"],
  },
  {
    id: "codyhouse",
    title: "CodyHouse",
    description: "A library of accessible HTML, CSS, JavaScript components.",
    url: "https://codyhouse.co/",
    category: "Tools",
    type: "Tool",
    tags: ["Components", "Accessibility"],
  },
  {
    id: "tympanus",
    title: "Codrops",
    description: "Creative front-end resources and inspiration.",
    url: "https://tympanus.net/codrops/",
    category: "Tools",
    type: "Guide",
    tags: ["Inspiration", "Animation"],
  },
  {
    id: "public-apis",
    title: "Public APIs",
    description:
      "A collective list of free APIs for use in software and web development.",
    url: "https://publicapis.io/",
    category: "Tools",
    type: "Documentation",
    tags: ["API", "List"],
  },
  {
    id: "svgviewer",
    title: "SVG Viewer",
    description: "An online tool to view, edit, and optimize SVG files.",
    url: "https://www.svgviewer.dev/",
    category: "Tools",
    type: "Tool",
    tags: ["SVG", "Optimization"],
  },
  {
    id: "jsonformatter",
    title: "JSON Formatter",
    description: "Online JSON Formatter and Validator.",
    url: "https://jsonformatter.org/",
    category: "Tools",
    type: "Tool",
    tags: ["JSON", "Formatter"],
  },
  {
    id: "jsonplaceholder",
    title: "JSONPlaceholder",
    description: "Free fake API for testing and prototyping.",
    url: "https://jsonplaceholder.typicode.com/",
    category: "Tools",
    type: "Tool",
    tags: ["API", "Mock"],
  },
  {
    id: "codeshare",
    title: "Codeshare",
    description: "Share code in real-time with other developers.",
    url: "https://codeshare.io/",
    category: "Tools",
    type: "Tool",
    tags: ["Collaboration", "Real-time"],
  },
  {
    id: "jsfiddle",
    title: "JSFiddle",
    description:
      "Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.",
    url: "https://jsfiddle.net/",
    category: "Tools",
    type: "Playground",
    tags: ["Editor", "Online"],
  },
  {
    id: "hoppscotch",
    title: "Hoppscotch",
    description: "Open source API development ecosystem.",
    url: "https://hoppscotch.io/",
    category: "Tools",
    type: "Tool",
    tags: ["API", "Testing"],
  },
  {
    id: "realfavicongenerator",
    title: "Real Favicon Generator",
    description: "The ultimate favicon generator for all platforms.",
    url: "https://realfavicongenerator.net/",
    category: "Tools",
    type: "Generator",
    tags: ["Favicon", "Design"],
  },
  {
    id: "favicon-io",
    title: "Favicon.io",
    description: "The only favicon generator you need for your next project.",
    url: "https://favicon.io/",
    category: "Tools",
    type: "Generator",
    tags: ["Favicon", "Design"],
  },
  {
    id: "cssgenerator-pl",
    title: "CSS Generator PL",
    description: "A comprehensive collection of CSS generators.",
    url: "https://cssgenerator.pl/",
    category: "CSS",
    type: "Generator",
    tags: ["Polish", "Generators"],
  },
  {
    id: "coursehunter",
    title: "CourseHunter",
    description: "A platform for finding and sharing development courses.",
    url: "https://coursehunter.net/",
    category: "General",
    type: "Guide",
    tags: ["Courses", "Learning"],
  },
  {
    id: "hackfrontend",
    title: "HackFrontend",
    description: "Front-end development challenges and tutorials.",
    url: "https://www.hackfrontend.com/",
    category: "General",
    type: "Exercise",
    tags: ["Challenges", "Front-end"],
  },
  {
    id: "doka-guide",
    title: "Doka Guide",
    description: "A comprehensive guide to web development in Russian.",
    url: "https://doka.guide/",
    category: "General",
    type: "Documentation",
    tags: ["Russian", "Reference"],
  },
  {
    id: "nodebestpractices",
    title: "Node.js Best Practices",
    description: "The most comprehensive list of Node.js best practices.",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    category: "General",
    type: "Guide",
    tags: ["Node.js", "Backend", "Best Practices"],
  },
  {
    id: "overapi",
    title: "OverAPI",
    description: "Collecting all cheat sheets in one place.",
    url: "https://overapi.com/",
    category: "Tools",
    type: "Documentation",
    tags: ["Cheat Sheets", "Reference"],
  },
  {
    id: "devhints",
    title: "DevHints",
    description: "A collection of cheat sheets for developers.",
    url: "https://devhints.io/",
    category: "Tools",
    type: "Documentation",
    tags: ["Cheat Sheets", "Reference"],
  },
  {
    id: "quickref-me",
    title: "QuickRef.me",
    description: "Cheat sheets for developers and programmers.",
    url: "https://quickref.me/",
    category: "Tools",
    type: "Documentation",
    tags: ["Cheat Sheets", "Reference"],
  },
  {
    id: "regex-generator",
    title: "Regex Generator",
    description: "A tool to generate regular expressions from text.",
    url: "https://regex-generator.olafneumann.org/",
    category: "Tools",
    type: "Generator",
    tags: ["Regex", "Generator"],
  },
];
